name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.21.1'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Run linters
        run: pnpm run lint

      - name: Run formatters check
        run: pnpm run format:check

      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.cjs
